export const ORGANIZATION_ERROR_CODES = {
  organizationNotFound: "ORGANIZATION_NOT_FOUND",
  organizationAccessDenied: "ORGANIZATION_ACCESS_DENIED",
  applicationNotFound: "ORGANIZATION_APPLICATION_NOT_FOUND",
  applicationAccessDenied: "ORGANIZATION_APPLICATION_ACCESS_DENIED",
  invalidApplicationTransition: "INVALID_APPLICATION_TRANSITION",
  notActivatable: "ORGANIZATION_NOT_ACTIVATABLE",
  activationRequirementsIncomplete: "ACTIVATION_REQUIREMENTS_INCOMPLETE",
  organizationNotActive: "ORGANIZATION_NOT_ACTIVE",
  alreadyActive: "ORGANIZATION_ALREADY_ACTIVE",
  suspended: "ORGANIZATION_SUSPENDED",
  requirementNotFound: "ACTIVATION_REQUIREMENT_NOT_FOUND",
  membershipNotFound: "MEMBERSHIP_NOT_FOUND",
  membershipInactive: "MEMBERSHIP_INACTIVE",
  permissionDenied: "PERMISSION_DENIED",
  storeNotFound: "STORE_NOT_FOUND",
  storeAccessDenied: "STORE_ACCESS_DENIED",
  invalidStoreScope: "INVALID_STORE_SCOPE",
  lastOrganizationOwner: "LAST_ORGANIZATION_OWNER",
  ownerRoleAssignmentForbidden: "OWNER_ROLE_ASSIGNMENT_FORBIDDEN",
  ownerMutationForbidden: "OWNER_MUTATION_FORBIDDEN",
  crossOrganizationStoreScope: "CROSS_ORGANIZATION_STORE_SCOPE",
  membershipAlreadyExists: "MEMBERSHIP_ALREADY_EXISTS",
  invalidRoleStoreScope: "INVALID_ROLE_STORE_SCOPE",
} as const;

export const ORGANIZATION_AUDIT_ACTIONS = {
  applicationCreated: "ORGANIZATION_APPLICATION_CREATED",
  applicationSubmitted: "ORGANIZATION_APPLICATION_SUBMITTED",
  reviewStarted: "ORGANIZATION_APPLICATION_REVIEW_STARTED",
  informationRequested: "ORGANIZATION_APPLICATION_INFORMATION_REQUESTED",
  applicationApproved: "ORGANIZATION_APPLICATION_APPROVED",
  applicationRejected: "ORGANIZATION_APPLICATION_REJECTED",
  activationRequirementCreated: "ORGANIZATION_ACTIVATION_REQUIREMENT_CREATED",
  activationRequirementSatisfied:
    "ORGANIZATION_ACTIVATION_REQUIREMENT_SATISFIED",
  activationRequirementWaived: "ORGANIZATION_ACTIVATION_REQUIREMENT_WAIVED",
  organizationActivated: "ORGANIZATION_ACTIVATED",
  organizationSuspended: "ORGANIZATION_SUSPENDED",
  organizationUpdated: "ORGANIZATION_UPDATED",
  storeCreated: "STORE_CREATED",
  storeUpdated: "STORE_UPDATED",
  storeArchived: "STORE_ARCHIVED",
  membershipCreated: "MEMBERSHIP_CREATED",
  membershipRoleChanged: "MEMBERSHIP_ROLE_CHANGED",
  membershipScopeChanged: "MEMBERSHIP_SCOPE_CHANGED",
  membershipSuspended: "MEMBERSHIP_SUSPENDED",
  membershipReactivated: "MEMBERSHIP_REACTIVATED",
} as const;
