FROM node:22-alpine

RUN apk add --no-cache openssl

EXPOSE 3000

WORKDIR /app

ENV NODE_ENV=production

COPY integrations/shopify/package.json integrations/shopify/package-lock.json ./

RUN npm ci

COPY tsconfig.base.json /tsconfig.base.json
COPY integrations/shopify/ ./

RUN npm run build

RUN npm prune --omit=dev && npm cache clean --force

CMD ["npm", "run", "docker-start"]
