# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52e96ba0f2c2a416cfe9ccc6136c28b8"
name = "selfx-tryon"
application_url = "https://fashion-try-on-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_products,write_app_proxy"

[auth]
redirect_urls = [
  "https://fashion-try-on-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2026-07"

[app_proxy]
url = "/apps/selfx-tryon"
subpath = "selfx-tryon"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
