# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52e96ba0f2c2a416cfe9ccc6136c28b8"
name = "selfx-tryon"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
